import { Bell, Building2, Check, Database, Info, Mail, MessageCircle, RotateCcw, ScanFace, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import PageHeader from '../components/PageHeader'
import { useData } from '../context/DataContext'

export default function SettingsPage() {
  const { settings, saveSettings, resetDemo } = useData()
  const [form, setForm] = useState(settings)
  const [saved, setSaved] = useState(false)
  const [confirmReset, setConfirmReset] = useState(false)
  function change(event) { const { name, value, checked, type } = event.target; setForm((current) => ({ ...current, [name]: type === 'checkbox' ? checked : value })) }
  function submit(event) { event.preventDefault(); saveSettings(form); setSaved(true); setTimeout(() => setSaved(false), 2500) }
  function reset() { resetDemo(); setForm(settings); setConfirmReset(false); window.location.reload() }
  return <div className="page settings-page"><PageHeader eyebrow="Administração" title="Configurações" description="Personalize os dados e o comportamento do COGEM." />
    <form onSubmit={submit} className="settings-grid">
      <section className="panel settings-section"><header><span><Building2 size={20} /></span><div><h2>Dados do condomínio</h2><p>Informações exibidas em telas e relatórios.</p></div></header><div className="form-layout"><label className="span-2"><span>Nome do condomínio</span><input name="condominiumName" value={form.condominiumName} onChange={change} /></label><label><span>CNPJ/Documento</span><input name="document" value={form.document} onChange={change} /></label><label><span>Cidade/Endereço</span><input name="address" value={form.address} onChange={change} /></label></div></section>
      <section className="panel settings-section"><header><span><Bell size={20} /></span><div><h2>Notificações e automações</h2><p>Escolha quais eventos geram alertas.</p></div></header><div className="settings-toggles"><label><span><strong>Encomendas</strong><small>Avisar sobre novos volumes recebidos.</small></span><input type="checkbox" name="packageNotifications" checked={form.packageNotifications} onChange={change} /></label><label><span><strong><MessageCircle size={15} /> WhatsApp</strong><small>Enviar mensagens e QR de retirada.</small></span><input type="checkbox" name="whatsappNotifications" checked={form.whatsappNotifications ?? true} onChange={change} /></label><label><span><strong><Mail size={15} /> E-mail</strong><small>Enviar confirmações e protocolos.</small></span><input type="checkbox" name="emailNotifications" checked={form.emailNotifications ?? true} onChange={change} /></label><label><span><strong>Visitantes</strong><small>Avisar entradas e saídas registradas.</small></span><input type="checkbox" name="visitorNotifications" checked={form.visitorNotifications} onChange={change} /></label><label><span><strong>Ocorrências</strong><small>Avisar novas solicitações urgentes.</small></span><input type="checkbox" name="occurrenceNotifications" checked={form.occurrenceNotifications} onChange={change} /></label><label><span><strong><ScanFace size={15} /> Reconhecimento facial</strong><small>Habilitar validação biométrica no acesso.</small></span><input type="checkbox" name="facialAccess" checked={form.facialAccess ?? true} onChange={change} /></label></div></section>
      <section className="panel settings-section"><header><span><ShieldCheck size={20} /></span><div><h2>Segurança e integração</h2><p>Status dos recursos que dependem do backend.</p></div></header><div className="integration-list"><div><Database size={18} /><span><strong>Modo de dados</strong><small>Dados locais demonstrativos</small></span><b className="status-dot warning">local</b></div><div><ShieldCheck size={18} /><span><strong>Permissões</strong><small>Interface preparada por função</small></span><b className="status-dot success">ativa</b></div><div><Info size={18} /><span><strong>API Python</strong><small>Contrato disponível na documentação</small></span><b className="status-dot neutral">pendente</b></div></div></section>
      <section className="panel settings-section danger-section"><header><span><RotateCcw size={20} /></span><div><h2>Dados de demonstração</h2><p>Restaure os exemplos originais do frontend.</p></div></header>{confirmReset ? <div className="reset-confirm"><p>Todos os cadastros feitos localmente serão apagados. Deseja continuar?</p><div><button type="button" className="button secondary" onClick={() => setConfirmReset(false)}>Cancelar</button><button type="button" className="button danger" onClick={reset}>Sim, restaurar</button></div></div> : <button type="button" className="button danger-outline" onClick={() => setConfirmReset(true)}><RotateCcw size={16} />Restaurar dados iniciais</button>}</section>
      <footer className="settings-actions">{saved && <span><Check size={17} />Configurações salvas</span>}<button className="button primary"><Check size={17} />Salvar configurações</button></footer>
    </form>
  </div>
}
